CREATE TABLE IF NOT EXISTS empleado_fotos (
  dni VARCHAR(32) NOT NULL PRIMARY KEY,
  mime_type VARCHAR(32) NOT NULL,
  ext VARCHAR(8) NOT NULL,
  data LONGBLOB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
